services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  redis:
    image: redis:7.2-bookworm
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    volumes:
      - /Users/david/tech4dev/v2/bootcamp/docker/data:/var/lib/postgresql/data
# volumes:
#   db_data:
